### ISSUE TITLE
cannot load such file -- cucumber/feature_file (LoadError)

### ISSUE THREAD

**Issue by ezhaka** [enkessler/cuketagger#1] opened 2016-04-06 12:53 UTC
trying to run `cuketagger`:

```
$ cuketagger
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- cucumber/feature_file (LoadError)
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/jarib-cuketagger-0.7.2/lib/cuketagger.rb:4:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/jarib-cuketagger-0.7.2/bin/cuketagger:4:in `<top (required)>'
        from /usr/local/bin/cuketagger:23:in `load'
        from /usr/local/bin/cuketagger:23:in `<main>'
```

**Comment by enkessler** [comment] 2016-04-06 14:45
That looks like a super old version of the gem. Like, 'not even on the RubyGems site anymore' old. As much as I'd like to help you out, trying to fix a problem that is before my time as maintainer of this library and for a version that is around 7 years old may be a bit more effort than its worth.

Have you tried using a newer version of the gem?

Edit: Oh, and if I had to guess, I suspect that newer versions of Cucumber no longer have that particular file in the same place as whatever version of Cucumber the 0.7.2 cuketagger was designed against.

**Comment by enkessler** [comment] 2016-06-24 14:03
@mcgee I'm going to assume that things worked out for you and I will be closing this issue soon.

**Closed as completed** 2016-11-26 13:15 UTC
